In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('healthcare_dataset.csv', header = 0)

#import library python dan datasets

In [5]:
df.tail() # melihat data dari bawah/akhir

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [6]:
df.head() #menampilkan data dari atas

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [7]:
df.sample(5) # Menampilkan 5 data acak

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
141,riTA archER,20,Male,O-,Diabetes,2024-01-05,Victoria Gonzales,"and Marquez Silva Smith,",Medicare,48995.980592,406,Elective,2024-02-04,Lipitor,Normal
48709,jereMy kElLey,37,Male,B+,Hypertension,2021-10-17,Wanda Castro MD,PLC Peters,Medicare,31076.246393,122,Urgent,2021-11-11,Ibuprofen,Abnormal
9730,kImbErLY WalkeR,33,Male,O-,Asthma,2020-03-28,Charles Yang,Reilly-Miller,Aetna,764.723183,364,Elective,2020-04-25,Penicillin,Inconclusive
34482,PaMeLa PAyNe,60,Male,O-,Diabetes,2021-06-28,Mikayla Walker,Davis-Gentry,UnitedHealthcare,47461.813532,495,Urgent,2021-07-16,Penicillin,Abnormal
50032,DR. KaTIe CooK,33,Male,AB-,Asthma,2021-10-15,Jacob Walker,"Guzman Smith and Price,",UnitedHealthcare,46058.129263,178,Urgent,2021-11-06,Paracetamol,Abnormal

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.4 MB

In [11]:
df.describe() # Menampilkan Statistik

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [12]:
df.isna().any()

Name                  False
Age                   False
Gender                False
Blood Type            False
Medical Condition     False
Date of Admission     False
Doctor                False
Hospital              False
Insurance Provider    False
Billing Amount        False
Room Number           False
Admission Type        False
Discharge Date        False
Medication            False
Test Results          False
dtype: bool

In [6]:
df.columns # Menamoilkan nama nama kolom

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='str')

In [8]:
df1 = pd.read_csv('Datasets/netflix1')

df1.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Datasets/netflix1'