In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('healthcare_dataset.csv', header = 0)

In [4]:
df.iloc[30:50, 2:12] # menampilkan data dari baris 30-50, dan dari kolom 2-12

,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type
30,Male,B-,Asthma,2019-08-18,Jacob Huynh,Hart Ltd,Cigna,47909.128810,371,Urgent
31,Female,A+,Arthritis,2019-11-03,Kristina Frazier,Cruz-Santiago,UnitedHealthcare,25835.323595,108,Urgent
32,Male,AB-,Arthritis,2023-05-18,John Hartman,Group Duncan,Medicare,17993.226200,245,Elective
33,Male,AB-,Cancer,2023-05-24,Heather Garcia,Lopez-Phillips,Medicare,21185.953530,494,Elective
34,Female,AB+,Diabetes,2020-01-17,Lynn Young,Poole Inc,Blue Cross,8408.949354,285,Emergency
35,Female,AB+,Asthma,2021-01-07,Emma Allison,Sons and Cox,Medicare,45453.418546,228,Elective
36,Male,AB+,Diabetes,2019-10-14,Laura Myers,LLC Martin,Aetna,4397.776995,481,Urgent
37,Female,B-,Hypertension,2021-12-19,Travis Parsons,Espinoza-Stone,Aetna,9380.325968,212,Urgent
38,Female,O-,Diabetes,2022-03-12,Christine Johnson,"and Garcia Morris Cunningham,",Cigna,48290.693407,113,Emergency
39,Female,B-,Obesity,2021-01-17,Emily Taylor,Walton-Meyer,Medicare,32973.940833,272,Urgent
40,Female,B-,Hypertension,2021-09-15,William Reynolds,PLC Young,Cigna,49943.278499,478,Emergency
41,Male,A+,Hypertension,2020-01-27,Jennifer Carter,Meadows Group,Cigna,35633.955454,196,Urgent
42,Female,A-,Asthma,2022-06-24,Matthew Thomas,"and Howell Brooks, Rogers",Cigna,25966.328610,418,Elective
43,Female,AB+,Obesity,2021-06-09,Mary Logan,"and Mcclure White Boone,",UnitedHealthcare,21784.445071,410,Urgent
44,Female,AB-,Cancer,2020-08-23,Kristin Martinez,"Gates Brown, and Stuart",Medicare,42684.558885,328,Urgent
45,Male,O+,Cancer,2022-10-12,Daniel Murphy,Group Armstrong,Medicare,45585.886560,300,Emergency
46,Female,O+,Hypertension,2021-12-01,Emily Patterson,Ltd Schwartz,Cigna,29615.441864,211,Elective
47,Male,A-,Diabetes,2020-05-04,Heather Smith,Nelson-Phillips,Cigna,36992.273688,413,Urgent
48,Male,O+,Hypertension,2023-09-09,John Smith,"Knight and Nguyen, Riggs",UnitedHealthcare,28051.499484,157,Urgent
49,Female,O+,Asthma,2019-07-19,Cameron Young,Lopez PLC,Cigna,16320.232447,138,Urgent

In [5]:
df.loc[30:50, ['Gender', 'Doctor']] # Menampilkan baris data dari 30-50 dan data Gender dan Doctor saja

    Gender             Doctor
30    Male        Jacob Huynh
31  Female   Kristina Frazier
32    Male       John Hartman
33    Male     Heather Garcia
34  Female         Lynn Young
35  Female       Emma Allison
36    Male        Laura Myers
37  Female     Travis Parsons
38  Female  Christine Johnson
39  Female       Emily Taylor
40  Female   William Reynolds
41    Male    Jennifer Carter
42  Female     Matthew Thomas
43  Female         Mary Logan
44  Female   Kristin Martinez
45    Male      Daniel Murphy
46  Female    Emily Patterson
47    Male      Heather Smith
48    Male         John Smith
49  Female      Cameron Young
50    Male       Vicki Nguyen

In [ ]:
df.loc[df['Gender'] == ''Male]