In [2]:
import pandas as pd

data = {
    'ID' : [1,2,3,4,2],
    'Name' : ['sapri', 'udin', 'saep','ujang', 'udin']
}

df = pd.DataFrame(data)
df

   ID   Name
0   1  sapri
1   2   udin
2   3   saep
3   4  ujang
4   2   udin

In [5]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [9]:
percentage_duplicated = ( df.duplicated().sum() / len(df)) * 100
percentage_duplicated

np.float64(20.0)

In [12]:
df_clean_duplicates = df.drop_duplicates()
df_clean_duplicates

   ID   Name
0   1  sapri
1   2   udin
2   3   saep
3   4  ujang

In [13]:
df.duplicated(subset='ID') # Mendeteksi duplikat berdasarkn kolom contoh kolom ID

0    False
1    False
2    False
3    False
4     True
dtype: bool